# Generated by Django 5.0.6 on 2024-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
